sudo: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email: sobreiro.pedro@gmail.com
  api_key:
    secure: Kq+bUaNRkTVEgK8oXxnBbTTZX/4yF71PWvSR+5q2ivNccJOohC0joKPctHA0wqLaLQO8Tq2mjZH7bjdYhiQmiATHFC790+T+ZRaX46/wsS0NhKCviSl9rRugJEzj/onwC2YYzzluL8a4an6WITMbF3HQrOgOtqXjGV4aM8PAPD8b1eWxSubpyuWvYVNNauIfjwDxDndxAiYZ6vDzs2SgVDQXDqSFkJyV1Bw0PX6YJJOLkNiLcceOVEjPV1vq7LR9J0ALOSpB+qIUcyF0EVoqqxCpsVtaMCwgPk8kRqruG7pf1TPKaWGkjcJaM+1q+mHPnfo3hz3ak/1U8PCO8VZ+R6qoVAr+Q3LrzMk+DD7GeM7cSQhkBj7t36sceXFlU/MCZen3/CiXMdRATGp2pQtNfWgPNZe8iDePzW/8yh777rOcVw4jKimfQWjN6nIRJHt1UsIb2vBYnKarOHRdXOOoPsbcC1fSsLnES+H46I64N8iOuAQyxB1+TF2dZP7Ms+GMns5s4UD8bBEXZosFQcd+OO4NTuB2pWTvRHTZd1zKDe9PixwGfY3H/1j/uCzpKyLmZ7F65qHG8XhiQdGZ+tWum3xuY6xZ2XVhzf+1hKMo8oLANfNXRcJvjWqGrhch8Qtwh6tO5ehu4jENayp8t95mMXfhNrp4qfIt1c1bqXlkdDQ=
  on:
    tags: true
    repo: criticalmanufacturing/dev-tasks
